version: "3"
services:
  postgres:
    image: "postgres"
    container_name: "my_postgres"
    environment:
      - POSTGRES_USER:postgres
      - POSTGRES_PASSWORD:postgres      
    ports:
      - "54320:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "redisdata:/data"

volumes:
  my_dbdata:
  redisdata: