definitions:
  models.AddUser:
    properties:
      email:
        type: string
      is_admin:
        type: boolean
      name:
        type: string
      password:
        type: string
      telp:
        type: string
    type: object
  models.ForgotForm:
    properties:
      account:
        type: string
    type: object
  models.LoginForm:
    properties:
      account:
        type: string
      pwd:
        type: string
    type: object
  models.OrderDPost:
    properties:
      durasi_end:
        type: integer
      durasi_start:
        type: integer
      paket_id:
        type: integer
      paket_name:
        type: string
      price:
        type: number
    type: object
  models.OrderPost:
    properties:
      barber_id:
        type: integer
      capster_id:
        type: integer
      customer_name:
        type: string
      order_date:
        type: integer
      paket_ids:
        items:
          $ref: '#/definitions/models.OrderDPost'
        type: array
      telp:
        type: string
      user_id:
        type: integer
    type: object
  models.RegisterForm:
    properties:
      account:
        type: string
      confirm_pwd:
        type: string
      name:
        type: string
      pwd:
        type: string
      user_type:
        type: string
    type: object
  models.ResetPasswd:
    properties:
      account:
        type: string
      confirm_pwd:
        type: string
      pwd:
        type: string
    type: object
  models.ResponseModelList:
    properties:
      all_column:
        type: string
      data:
        type: object
      define_column:
        type: string
      define_size:
        type: string
      last_page:
        type: integer
      message:
        type: string
      page:
        type: integer
      total:
        type: integer
    type: object
  models.UpdateUser:
    properties:
      email:
        type: string
      name:
        type: string
      telp:
        type: string
    type: object
  models.VerifyForm:
    properties:
      account:
        type: string
      verify_code:
        type: string
    type: object
  tool.ResponseModel:
    properties:
      data:
        type: object
      message:
        description: Code int         `json:"code"`
        type: string
    type: object
info:
  contact:
    email: nuryantofattih@gmail.com
    name: Nuryanto
    url: https://www.linkedin.com/in/nuryanto-1b2721156/
  description: Backend REST API for golang nuryanto2121
  license: {}
  title: Starter
  version: "1.0"
paths:
  /api/fileupload:
    post:
      consumes:
      - multipart/form-data
      description: Upload file
      parameters:
      - description: OS Device
        in: header
        name: OS
        required: true
        type: string
      - description: OS Device
        in: header
        name: Version
        required: true
        type: string
      - description: account image
        in: formData
        name: upload_file
        required: true
        type: file
      - description: path images
        in: formData
        name: path
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tool.ResponseModel'
      security:
      - ApiKeyAuth: []
      summary: File Upload
      tags:
      - FileUpload
  /barber/auth/change_password:
    post:
      parameters:
      - description: OS Device
        in: header
        name: OS
        required: true
        type: string
      - description: OS Device
        in: header
        name: Version
        required: true
        type: string
      - description: 'req param #changes are possible to adjust the form of the registration
          form from frontend'
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/models.ResetPasswd'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tool.ResponseModel'
      summary: Change Password
      tags:
      - Auth
  /barber/auth/forgot:
    post:
      parameters:
      - description: OS Device
        in: header
        name: OS
        required: true
        type: string
      - description: OS Device
        in: header
        name: Version
        required: true
        type: string
      - description: 'req param #changes are possible to adjust the form of the registration
          form from frontend'
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/models.ForgotForm'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tool.ResponseModel'
      summary: Forgot Password
      tags:
      - Auth
  /barber/auth/login:
    post:
      parameters:
      - description: OS Device
        in: header
        name: OS
        required: true
        type: string
      - description: OS Device
        in: header
        name: Version
        required: true
        type: string
      - description: 'req param #changes are possible to adjust the form of the registration
          form from frontend'
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/models.LoginForm'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tool.ResponseModel'
      summary: Login
      tags:
      - Auth
  /barber/auth/register:
    post:
      parameters:
      - description: OS Device
        in: header
        name: OS
        required: true
        type: string
      - description: OS Device
        in: header
        name: Version
        required: true
        type: string
      - description: 'req param #changes are possible to adjust the form of the registration
          form from frontend'
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/models.RegisterForm'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tool.ResponseModel'
      summary: Register
      tags:
      - Auth
  /barber/auth/verify:
    post:
      parameters:
      - description: OS Device
        in: header
        name: OS
        required: true
        type: string
      - description: OS Device
        in: header
        name: Version
        required: true
        type: string
      - description: 'req param #changes are possible to adjust the form of the registration
          form from frontend'
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/models.VerifyForm'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tool.ResponseModel'
      summary: Verify
      tags:
      - Auth
  /barber/order:
    get:
      parameters:
      - description: OS Device
        in: header
        name: OS
        required: true
        type: string
      - description: OS Device
        in: header
        name: Version
        required: true
        type: string
      - description: Page
        in: query
        name: page
        required: true
        type: integer
      - description: PerPage
        in: query
        name: perpage
        required: true
        type: integer
      - description: Search
        in: query
        name: search
        type: string
      - description: InitSearch
        in: query
        name: initsearch
        type: string
      - description: SortField
        in: query
        name: sortfield
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ResponseModelList'
      security:
      - ApiKeyAuth: []
      summary: GetList Order
      tags:
      - Order
    post:
      parameters:
      - description: OS Device
        in: header
        name: OS
        required: true
        type: string
      - description: OS Device
        in: header
        name: Version
        required: true
        type: string
      - description: 'req param #changes are possible to adjust the form of the registration
          form from frontend'
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/models.OrderPost'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tool.ResponseModel'
      security:
      - ApiKeyAuth: []
      summary: Add Order
      tags:
      - Order
  /barber/order/{id}:
    delete:
      parameters:
      - description: OS Device
        in: header
        name: OS
        required: true
        type: string
      - description: OS Device
        in: header
        name: Version
        required: true
        type: string
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tool.ResponseModel'
      security:
      - ApiKeyAuth: []
      summary: Delete Order
      tags:
      - Order
    get:
      parameters:
      - description: OS Device
        in: header
        name: OS
        required: true
        type: string
      - description: OS Device
        in: header
        name: Version
        required: true
        type: string
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tool.ResponseModel'
      security:
      - ApiKeyAuth: []
      summary: GetById
      tags:
      - Order
    put:
      parameters:
      - description: OS Device
        in: header
        name: OS
        required: true
        type: string
      - description: OS Device
        in: header
        name: Version
        required: true
        type: string
      - description: ID
        in: path
        name: id
        required: true
        type: string
      - description: 'req param #changes are possible to adjust the form of the registration
          form from frontend'
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/models.OrderPost'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tool.ResponseModel'
      security:
      - ApiKeyAuth: []
      summary: Rubah Profile
      tags:
      - Order
  /barber/user:
    get:
      parameters:
      - description: OS Device
        in: header
        name: OS
        required: true
        type: string
      - description: OS Device
        in: header
        name: Version
        required: true
        type: string
      - description: Page
        in: query
        name: page
        required: true
        type: integer
      - description: PerPage
        in: query
        name: perpage
        required: true
        type: integer
      - description: Search
        in: query
        name: search
        type: string
      - description: InitSearch
        in: query
        name: initsearch
        type: string
      - description: SortField
        in: query
        name: sortfield
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ResponseModelList'
      security:
      - ApiKeyAuth: []
      summary: GetList User
      tags:
      - User
    post:
      parameters:
      - description: OS Device
        in: header
        name: OS
        required: true
        type: string
      - description: OS Device
        in: header
        name: Version
        required: true
        type: string
      - description: 'req param #changes are possible to adjust the form of the registration
          form from frontend'
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/models.AddUser'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tool.ResponseModel'
      security:
      - ApiKeyAuth: []
      summary: Add User
      tags:
      - User
  /barber/user/{id}:
    delete:
      parameters:
      - description: OS Device
        in: header
        name: OS
        required: true
        type: string
      - description: OS Device
        in: header
        name: Version
        required: true
        type: string
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tool.ResponseModel'
      security:
      - ApiKeyAuth: []
      summary: Delete User
      tags:
      - User
    get:
      parameters:
      - description: OS Device
        in: header
        name: OS
        required: true
        type: string
      - description: OS Device
        in: header
        name: Version
        required: true
        type: string
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tool.ResponseModel'
      security:
      - ApiKeyAuth: []
      summary: GetById
      tags:
      - User
    put:
      parameters:
      - description: OS Device
        in: header
        name: OS
        required: true
        type: string
      - description: OS Device
        in: header
        name: Version
        required: true
        type: string
      - description: ID
        in: path
        name: id
        required: true
        type: string
      - description: 'req param #changes are possible to adjust the form of the registration
          form from frontend'
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/models.UpdateUser'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tool.ResponseModel'
      security:
      - ApiKeyAuth: []
      summary: Rubah Profile
      tags:
      - User
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
